// This file is generated by Slice Machine. Update with care!

import CardBiens from './CardBiens';
import Details from './Details';

export {
	CardBiens,
	Details,
};

export const components = {
	card_biens: CardBiens,
	details: Details,
};
