// Code generated by Slice Machine. DO NOT EDIT.

import CardBiens from './CardBiens';
import Details from './Details';

export {
	CardBiens,
	Details,
};

export const components = {
	card_biens: CardBiens,
	details: Details,
};
